### ISSUE TITLE
Using a tessellated object to do a boolean difference on another object doesn't fully do the boolean difference

### ISSUE THREAD

**Issue by stillpointx** [alessandro-zomparelli/tissue#100]
Using tessellated object to do a boolean difference on another object doesn't fully do the boolean difference

When I create a tessellated object on **selected faces** and then do a **boolean difference** on another object using the tessellated object **not all of the boolean differences are applied**.   

**Tessellated object on 3 selected faces:**

![screenshot-2021-02-07-07-53-01](https://user-images.githubusercontent.com/28985314/107147071-0f330480-691a-11eb-87e8-708712f66cda.png)

**When applying a boolean difference to the 3 faces only 1 gets applied:**

![screenshot-2021-02-07-07-54-50](https://user-images.githubusercontent.com/28985314/107147065-ffb3bb80-6919-11eb-9ef9-bf8f4b89b7bd.png)

I'm Using Ubuntu 20.04, Blender 2.91.2, Tissue 0.3.48
I've attach the file if that helps.
[rotor.blend.zip](https://github.com/alessandro-zomparelli/tissue/files/5939017/rotor.blend.zip)

**Comment by JoelGodin** [comment]
This is blender boolean modifier, not the tissue addon.
There it this from the manual:
"Only Manifold meshes are guaranteed to give proper results, 
other cases (especially “opened” meshes, Non-manifold but 
without any self-intersections) will usually work well, but might 
give odd glitches and artifacts in some cases."

So if you close the cylinder and make it a manifold object, you get this:
![cone](https://user-images.githubusercontent.com/9205295/107150128-427d8f80-692a-11eb-9244-d3ec27a508fb.png)

**Comment by stillpointx** [comment]
Thanks!!
