### ISSUE TITLE
Tessellate modifier

### ISSUE THREAD

**Issue by Nicknroll** [alessandro-zomparelli/tissue#103]
Hi, first of all thank you for great work!

I'd like to ask, don't you have some plans to make Tessellate modifier for more dynamic workflow?
Actually is it possible?

**Comment by alessandro-zomparelli** [comment]
Hi @Nicknroll 
unfortunately is not possible at the moment to create modifiers with a simple add-on. This is something that must be added to the source code of Blender, and I'm not able at the moment to do that. Maybe Geometry-Nodes will open the possibility to customize it with Blender's API, but at the moment, this is not easy.

**Comment by Nicknroll** [comment]
Okay will wait for some changes.
Tissue definitely have to become part of Blender!
