### ISSUE TITLE
2.92 morph shape key error.

### ISSUE THREAD

**Issue by YUNPERO** [alessandro-zomparelli/tissue#106]
I used 2.91 version of tissue to blender 2.92. During studying morph part watching your youtube(https://www.youtube.com/watch?v=2Wcu9E0EGEM) I added new shape key to component and clicked refresh after that new shape key was disappeared also blender got error message.

component shape key.
![image](https://user-images.githubusercontent.com/82076650/113813359-ba412c80-97aa-11eb-9293-e96089fa0739.png)

base vertex group
![image](https://user-images.githubusercontent.com/82076650/113813447-e197f980-97aa-11eb-9993-655fba484bc3.png)

before clicked refresh button for second shape key.
![image](https://user-images.githubusercontent.com/82076650/113813617-30459380-97ab-11eb-874a-1c1a817d19c9.png)

after clicked refresh key. error occurred.
![image](https://user-images.githubusercontent.com/82076650/113813694-566b3380-97ab-11eb-9d67-fe1a7433052a.png)

I dont know why this was happened. collision of version?

+
It works find when fill mode is not patch. Just in patch mode, error occured.

**Comment by alessandro-zomparelli** [comment]
Hi @YUNPERO , thanks for reporting. Please, try to use the most recent update: https://github.com/alessandro-zomparelli/tissue/tree/b290-dev
and try again with a brand new tessellation. In case of error, please, send a screenshot of the console report.

**Comment by YUNPERO** [comment]
> Hi @YUNPERO , thanks for reporting. Please, try to use the most recent update: https://github.com/alessandro-zomparelli/tissue/tree/b290-dev
> and try again with a brand new tessellation. In case of error, please, send a screenshot of the console report.

Sorry. It was my mistake. My base object was not quad. Because I applied triangulate modifier before subdivision, Error was occurred.. :( Also I downloaded latest version 3.5. Thank you for beautiful addon.
