### ISSUE TITLE
Contour Curves 

### ISSUE THREAD

**Issue by vicapacheco** [alessandro-zomparelli/tissue#117]
Hello there I am writing here because I used a lot your amazing add on my 3d works.
I use mostly the Countour Curve, to create "stream lines" from vertex of an object.
But recently I updated blender and changed to 2.93
The functions are not the same, and I cant find how to do again this streamlines.
This is a video that explains what I used to do with tissua add on. We can see clarly that the menu deployed from contour curves is not the same than the one from the video.
I would love to know if this function still possible to do, or just what happened?

https://www.youtube.com/watch?v=_DlCIpNqcCU

Any way thank you so much.

best

Victoria

**Comment by JoelGodin** [comment]
They are in the weight paint section as in this video https://youtu.be/_DlCIpNqcCU?t=76

**Comment by vicapacheco** [comment]
Hello Joel, thanks for yout answer. Your video is exactly the same video I put on my question, the problem is that in my latest version of blender the option stream lines is not there anymore.

**Comment by JoelGodin** [comment]
Are you using the latest version of Tissue from here? 3.50 ?
Here's a pic of my 2.93 using 3.50 Tissue.
![1](https://user-images.githubusercontent.com/9205295/122307723-e67ad700-ced8-11eb-85f5-818581ca8a05.png)

**Comment by alessandro-zomparelli** [comment]
Thanks @JoelGodin . I think that this is the problem,
I have to fix this problem with this broken version of Tissue currently shipped with Blender.

**Comment by vicapacheco** [comment]
Hello Joel
Thanks so much for your time.
Yes im using, but maybe i am doing something wrong on the installation?

**Comment by vicapacheco** [comment]
WAHOOO
I arrived.
I deletade form the add ons folder the tissue folder coming with 2.93
then I installed de 3.5 version.

Thanks a lot 
im happy

**Comment by JoelGodin** [comment]
Awesome! Welcome aboard.  
When you get time, don't forget to close the issue.

Thanks
