### ISSUE TITLE
Convert Texture to Geometry?

### ISSUE THREAD

**Issue by melvixiodf** [alessandro-zomparelli/tissue#118]
@alessandro-zomparelli 
Hi alessandro.

Hope you are doing well.

Wanted to ask if this is possible with the tissue addon where is you have different colors on a texture. It can be used to generate a a tessellated mesh with edge loops generated where the colors meet.

This is possible in Maya:
https://knowledge.autodesk.com/support/maya/learn-explore/caas/CloudHelp/cloudhelp/2019/ENU/Maya-Modeling/files/GUID-79763ED5-E7BD-408B-937B-92743EDDF57A-htm.html

I am not sure if this is possible and if it is, can this be added as a feature?

Cheers,

**Comment by alessandro-zomparelli** [comment]
hi @melvixiodf 
sorry for the late reply. Really interesting feature. In Tissue you can operate on vertex groups generating contour loops according to the weight values using Contour Displace in Weight Paint mode.
![image](https://user-images.githubusercontent.com/6708848/127228245-ad906df2-d38e-4f2c-9321-b9f59c2dddc7.png)
This is an example of the result that you can get:
![image](https://user-images.githubusercontent.com/6708848/127228319-97caa77e-6814-4f07-93cf-68f1714e4f6e.png)

It's a different thing, but I think it's the closest thing that you can do with Tissue :-)

**Comment by melvixiodf** [comment]
Thanks for the suggestion, mate.
