### ISSUE TITLE
got this issue 

### ISSUE THREAD

**Issue by Totoro51212** [alessandro-zomparelli/tissue#120]
![image](https://user-images.githubusercontent.com/87871970/126814850-e86d9958-cf5f-4584-9efe-27f57b14bf96.png)

**Comment by JoelGodin** [comment]
Is that the version that comes with Blender, or did you download the code from Github here?

**Comment by Totoro51212** [comment]
> Is that the version that comes with Blender, or did you download the code from Github here?

i got it from here

**Comment by Totoro51212** [comment]
so first i unzipped and then tried it and it didnt do anything
then i got t he zipped one and tried it but it says this

**Comment by JoelGodin** [comment]
Yes, you are supposed to leave it zipped.

Be sure the other Tissue that comes with Blender is not checked (disabled) before installing this zip file.

**Comment by Totoro51212** [comment]
ahh, i cant get the unzipped file off though

**Comment by JoelGodin** [comment]
It should look like this (notice the versions):

![1](https://user-images.githubusercontent.com/9205295/126855243-892abd55-b3b3-46a5-abbd-ce536564d5b7.png)

**Comment by Totoro51212** [comment]
i did that but nothing shows in the side bar
