### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by Totoro51212** [alessandro-zomparelli/tissue#123]
![image](https://user-images.githubusercontent.com/87871970/127887682-fdcd16ed-5266-4979-b062-ea966abefddd.png)
got an error that doesnt let me tesselate

**Comment by alessandro-zomparelli** [comment]
@Totoro51212 this is a very old issue. I'm sorry for not replying to that, but I assume that this may be resolved in the latest version of Tissue. Can you please confirm that?
