### ISSUE TITLE
Tissue 0.3.52 with Blender 3.1 - Numba non working with Numpy 1.22

### ISSUE THREAD

**Issue by alessandro-zomparelli** [alessandro-zomparelli/tissue#132]
Blender 3.1 is shipped with Numpy 1.22. Unfortunately, the current version of Numba is only compatible with Numpy 1.21 (or older)

https://github.com/numba/numba/issues/7754

Unfortunately, seems also that Numpy 1.21 is not compatible with Python 3.10 (used in Blender 3.1).

@Blendify and @s-leger do you see a possible solution for that. Would a Python downgrade be possible/recommended? Maybe not officially, but as a possible turnaround to speed up Tissue.  

I also see that it may be possible to install a Numpy 1.21 from an unofficial wheel, but to I haven't tried anything like that: https://stackoverflow.com/questions/69458399/numpy-1-21-2-may-not-yet-support-python-3-10

**Comment by quantumscience** [comment]
Workaround for anybody, who has an issue with Tissue> To use Tissue with 3.1, you need to uncheck **Numba tesselate** in Preferences>Addons>Mesh:Tissue, under Print Stats. Otherwise, a python error pops up.

**Comment by alessandro-zomparelli** [comment]
With the latest update to Tissue (current master branch) the issue seems solved on Blender 3.3.1
