### ISSUE TITLE
Add-on not shipped with Blender 3.2 anymore

### ISSUE THREAD

**Issue by markste-in** [alessandro-zomparelli/tissue#134]
I am currently using Blender 3.2a and noticed that I was not able to find the tissue add-on anymore. I asked the support channel of the blender.chat and got the following response

_NiCapp @nicapp
12:01
Tissue add-on and 2 other was removed from Blender release cause manuals are host outside [b.ender.org](http://b.ender.org/) domain. In past weeks Blender was changed rules for code released with it, all code and related documents must be hosted inside Blender servers. You can reminder to add-on developer to complete this task ASAP and add-on will back._

I think the manual needs to move to b.ender.org so that the add-on can continue to ship with Blender?

**Comment by alessandro-zomparelli** [comment]
Thanks @markste-in for reporting that. I actually moved the documentation in the Blender manual. Still a WIP, but it's there. I'm also adding some other stuff now. I will try to contact them. Can you please give me the link of the conversation?

Thanks :-)

**Comment by markste-in** [comment]
Conversation can be found [here](https://blender.chat/channel/support?msg=yjvfBrv3cEFRHDv5h). Tho you need an account to see it.
