### ISSUE TITLE
Tessellation mode "FRAME"

### ISSUE THREAD

**Issue by cga558b** [alessandro-zomparelli/tissue#137]
I saw other reports about Frame Mode, but i don't know if this is different:

1 - as soon as you switch the fill mode to "Frame" the tessellation disappear, even with any further tweak doesn't seem to work (maybe because of my mistake, but the component is within the X 0 to 1 and Y 0 to 1 bounding and the base has all transformations applied, so I expect that something is shown at least)

2- as soon as you switch the fill mode to "Frame", a temporary object appears; and any tweak you make creates a new temporary object, even every minimum scroll creates a new one

Great addon BTW,
Thanx

**Comment by alessandro-zomparelli** [comment]
Thanks @cga558b for this report. I will close that since it's a resolved issue.
