### ISSUE TITLE
Every tessalation generates extra _mirror objects

### ISSUE THREAD

**Issue by bence-b** [alessandro-zomparelli/tissue#141]
Hi Alessandro,

First of all let me thank you for this great addon! I was jaust about to start experimenting with it but immediately run into a wierd issue. It seems, that if the _component_ has one or more mirror modifiers on it, any _modification_ on the object data properties of the _tessalation_ object results in extra objects in the scene. 

As if some kind of temporary obejcts were left behind. Please see the attached screenshot: The _detail_ obejct is the component. I was dragging the scale slider -> it updated the tessalation mesh 6 times while dragging --> created 6 _mirror objects in the scene. It happens on every UI button press. For example toggling the "Use modifiers" generates +1 object at each click.

![tissue_issue](https://user-images.githubusercontent.com/47229144/198638019-8319b2ec-f00f-4f5f-b777-8f09d2235f77.gif)

thanks for taking a look at it!
Ben

**Comment by alessandro-zomparelli** [comment]
Hi @bence-b thank you for your appreciation and for reporting this issue. 
It should be something that I already addressed. Are you using the latest version of Tissue? Try to use the current master branch. It should work properly.
Let me know

Alessandro

**Comment by bence-b** [comment]
hi, thank you for your answer.
Anyway, it's strange, I'm using the master branch, 0.3.53. I downloaded it the day I posted.

Ben

**Comment by alessandro-zomparelli** [comment]
I see. Is it also happening with the latest version (0.3.54)? When I try it seems working, but maybe you are doing something different. Do you want to share a file?

**Comment by bence-b** [comment]
0.3.54 is not available:)
https://github.com/alessandro-zomparelli/tissue/releases/tag/v0-3-54 gives 404

**Comment by alessandro-zomparelli** [comment]
Yes, you are right, that's because I didn't create the official release yet. But if you download it from the Master branch, then it should be the wip version of that

**Comment by bence-b** [comment]
ah, I don't konw why I didnt try that. Thank you, 0.3.54 works as expected.
Thank you!

**Comment by alessandro-zomparelli** [comment]
Perfect :-)
