### ISSUE TITLE
Cannot edit Tessellation once created: Error: user_resource() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by ryangodolphin** [alessandro-zomparelli/tissue#142]
When I create a Tessalted mesh, I am unable to go back and edit the original settings used to create that tesselation. I am following a tutorial and the tutor clicks on the generated tessellation to select it then goes to Tissue>Tessellate and is able to modify the settings used to create that tessellation. 

When I go to Blender Preferences > Add-ons > Mesh: Tissue under preferences there is an Error (see console) message. When viewing the console the error message user_resource() takes 1 positional argument but 2 were given is present across multiple lines. Not sure if this is causing the inability to edit the tessellation but it's also present. 

![Error](https://user-images.githubusercontent.com/36534320/207084008-1866a609-83ae-4255-b56d-25ae286215f0.png)

Currently, I am unable to edit the tessellated mesh.

**Comment by alessandro-zomparelli** [comment]
Hi @ryangodolphin did you try going to the Object data panel where the Tessellation settings are? Does it work from there?
![image](https://user-images.githubusercontent.com/6708848/217498128-6dcca30c-23a5-4e99-990f-1d8bbfd97c95.png)
