### ISSUE TITLE
Latest Tissue add-on

### ISSUE THREAD

**Issue by Whitton123** [alessandro-zomparelli/tissue#146]
Hi:)

Love this add-on and would like to resolve this issue as soon as possible, if possible.

Blender stable 3.4.1 on M1 iMac
Installed latest Tissue don from Github
Disabled default Blender Tissue and activated the new one

Keep getting this error (screenshots attached)
<img width="895" alt="Screenshot 2023-01-28 at 15 40 09" src="https://user-images.githubusercontent.com/75131239/215275574-83009baf-4c63-4fb0-be6d-3d17032e0a79.png">
:

Python: Traceback (most recent call last):
  File "/Users/m1imac/Library/Application Support/Blender/3.4/scripts/addons/tissue-master/tessellate_numpy.py", line 1811, in execute
    new_ob = convert_object_to_mesh(ob0, False, True, props.rotation_mode!='UV') #///
NameError: name 'props' is not defined
<img width="888" alt="Screenshot 2023-01-28 at 15 37 49" src="https://user-images.githubusercontent.com/75131239/215275448-eccd9797-f4d1-42a4-8066-d5f5e67cf418.png">

**Comment by dimitarsp** [comment]
Hi @alessandro-zomparelli. I am getting this error as well on windows 11 v 3.4.1 and tissue 0.3.55. If I create a tessellation initially with the budled Tissue version, then I can edit further with the updated version from here.

**Comment by alessandro-zomparelli** [comment]
Hi guys, I noticed that as well. I fixed that and the master branch is now updated. 
Please check if everything is fine for you :-)

**Comment by dimitarsp** [comment]
Thanks testing and confirmed that it works now. Cheers!
