### ISSUE TITLE
Materials in frame mode and component mode cannot be used(blender3.4)

### ISSUE THREAD

**Issue by mengmengddd** [alessandro-zomparelli/tissue#148]
![image](https://user-images.githubusercontent.com/97213157/224478907-6a836a2d-011a-4435-a70f-9d575bd31ee1.png),This object will appear in frame mode,Then the original tissue object disappears from the view

**Comment by alessandro-zomparelli** [comment]
> ![image](https://user-images.githubusercontent.com/97213157/224478907-6a836a2d-011a-4435-a70f-9d575bd31ee1.png),This object will appear in frame mode,Then the original tissue object disappears from the view
> 

Hi @mengmengddd thanks for reporting. Which version of Tissue are you using? Have you tried the last master branch? From my test this seems working.
Thanks
Alessandro

**Comment by mengmengddd** [comment]
![image](https://user-images.githubusercontent.com/97213157/224492922-91854709-5aff-4e42-96cd-fb092b325da2.png)
The version of Tissue is 0.3.52

**Comment by alessandro-zomparelli** [comment]
I see, it should be 0.3.57. Try to download and use instead this version: https://github.com/alessandro-zomparelli/tissue/archive/refs/heads/master.zip (is just the link from the master branch)
