### ISSUE TITLE
Cannot enable tissue anymore. Numba install error

### ISSUE THREAD

**Issue by NPDan87** [alessandro-zomparelli/tissue#149]
[blender.crash.txt](https://github.com/alessandro-zomparelli/tissue/files/11057090/blender.crash.txt)

After i enabled Numba, and it said installed succesfuly, i used tissue, after i closed it and opened blender it crashes instantly.
Clean opening blender without any addons works fine, however i now cannot enable tissue without an instant crash of blender.

Is there a way to uninstall Numba?  llvmlite seems to be the issue. 
I am a begginer at best in python and scripting but updating python3 and running: pip uninstall llvmlite fixed the issue. The addon can be used again with the message that numba module installed correctly.

Im preatty sure that what ive uninstalled should be used for something and i havent done a good job at this

i am using Ubuntu latest LTS up to date

Thanks great addon BTW

**Comment by alessandro-zomparelli** [comment]
Hi @NPDan87 ,
Thanks for reporting that. Are you using the latest version of Blender from GitHub (master branch) or the one shipped with Blender?
In theory llvmlite should be used for Numba. Removing it it's not ideal, but maybe is not used, I am not sure about that. Can you try importing Numba from the scripting console? Does it return any error? Have you successfully used the Reaction-Diffusion or the Tessellation?

**Comment by NPDan87** [comment]
> Hi @NPDan87 , Thanks for reporting that. Are you using the latest version of Blender from GitHub (master branch) or the one shipped with Blender? In theory llvmlite should be used for Numba. Removing it it's not ideal, but maybe is not used, I am not sure about that. Can you try importing Numba from the scripting console? Does it return any error? Have you successfully used the Reaction-Diffusion or the Tessellation?

OK, thanks for the response, I'll check into it and report later today

**Comment by NPDan87** [comment]
**>>> import numba**
"Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "/home/npdan/.local/lib/python3.10/site-packages/numba/__init__.py", line 19, in <module>
    from numba.core import config
  File "/home/npdan/.local/lib/python3.10/site-packages/numba/core/config.py", line 16, in <module>
    import llvmlite.binding as ll
ModuleNotFoundError: No module named 'llvmlite'"

**This is what i get when importing numba in blender, however it sais that its installed corectlly. Reaction diffusion works as it should however it maybe slower then it should 
linux console provs it** 

"119 Reaction-Diffusion: Plane
       Preparation Time: 0.009451627731323242
Not using Numba! The simulation could be slow.
       Simulation Time: 0.0333709716796875
       Writing Vertex Groups Time: 0.012867450714111328"

**After i reinstall llvmlite**
"pip install llvmlite
Defaulting to user installation because normal site-packages is not writeable
Collecting llvmlite
  Using cached llvmlite-0.39.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.6 MB)
Installing collected packages: llvmlite
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.56.4 requires numpy<1.24,>=1.18, which is not installed."

**Replacing the numpy version with  one between the indicated versions, i tried with 1.23.5, installs well 
After that i try installing again llvmlite**
"pip install llvmlite
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: llvmlite in ./.local/lib/python3.10/site-packages (0.39.1)"

Now every version of blender i try it wont open printing the crash log from the original post, until i remove llvmlite
To my very very very limited understanding about python this is due to differences in blenders version conflicts with ubuntu 22.04.02

**Comment by NPDan87** [comment]
**>>> import numba**
"Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "/home/npdan/.local/lib/python3.10/site-packages/numba/__init__.py", line 19, in <module>
    from numba.core import config
  File "/home/npdan/.local/lib/python3.10/site-packages/numba/core/config.py", line 16, in <module>
    import llvmlite.binding as ll
ModuleNotFoundError: No module named 'llvmlite'"

**This is what i get when importing numba in blender, however it sais that its installed corectlly. Reaction diffusion works as it should however it maybe slower then it should 
linux console provs it** 

"119 Reaction-Diffusion: Plane
       Preparation Time: 0.009451627731323242
Not using Numba! The simulation could be slow.
       Simulation Time: 0.0333709716796875
       Writing Vertex Groups Time: 0.012867450714111328"

**After i reinstall llvmlite**
"pip install llvmlite
Defaulting to user installation because normal site-packages is not writeable
Collecting llvmlite
  Using cached llvmlite-0.39.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.6 MB)
Installing collected packages: llvmlite
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.56.4 requires numpy<1.24,>=1.18, which is not installed."

**Replacing the numpy version with  one between the indicated versions, i tried with 1.23.5, installs well 
After that i try installing again llvmlite**
"pip install llvmlite
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: llvmlite in ./.local/lib/python3.10/site-packages (0.39.1)"

Now every version of blender i try it wont open printing the crash log from the original post, until i remove llvmlite
To my very very very limited understanding about python this is due to differences in blenders version conflicts with ubuntu 22.04.02
