### ISSUE TITLE
Undeclared variables

### ISSUE THREAD

**Issue by satabol** [alessandro-zomparelli/tissue#150]
Hi, Alessandro!
Blender 3.5, tissue-master-0.3.57.
I found two undeclared variables:
![image](https://user-images.githubusercontent.com/14288520/229469942-85a0c26f-1953-4547-8cde-697b7a209e34.png)
var "props" is simple, but I have no idea what is "data1"?

**Comment by alessandro-zomparelli** [comment]
Hi @satabol thanks for reporting that. I took care of that. 
Data1 is probably a leftover of some editing, for the time being, I will comment on those lines. It is not crucial, it was used to remove some generated mesh data in case of errors. 

Thanks
