### ISSUE TITLE
Vector Field Glitch

### ISSUE THREAD

**Issue by theobayard** [alessandro-zomparelli/tissue#155]
I am unable to use the vector field feature for reaction diffusions because every time I do the attached pattern propagates over the entire mesh. I've tried different object and different files. All with the same outcome. Any help would be greatly appreciated. Thank you for this amazing plugin!
 
![Tissue_Issue](https://github.com/alessandro-zomparelli/tissue/assets/41492964/6404de31-7a1b-478d-967e-dd5bbbd6e7ff)
![Tissue_Settings](https://github.com/alessandro-zomparelli/tissue/assets/41492964/929d51a5-b30a-4fbb-ae92-dccc49a00021)

**Comment by alessandro-zomparelli** [comment]
Hi @theobayard ,
the reaction-diffusion pattern, for some settings, could generate very high values that lead to this type of numerical error. In those cases, you should reduce the parameter dt, which will lead to smaller time steps reducing the errors. 
I understand your confusion, and the possible confusion of other users, for that reason I will double check the default settings :-)

**Comment by alessandro-zomparelli** [comment]
I will mark this as resolved since I updated Tissue with a default value for dt=0.5. Feel free to open a new thread if you still have problems
