### ISSUE TITLE
Issue with Tissue v0.3.66 for Blender 4.0.2 (Error: See Console Prompt)

### ISSUE THREAD

**Issue by alpoco** [alessandro-zomparelli/tissue#163]
Hi, everyone

Console is prompting me this error after installation:

![image](https://github.com/alessandro-zomparelli/tissue/assets/64455774/68956017-9c65-4eb1-b5d5-f5466bfa5a89)

Appreciate any guidance as to why this might be happening.

**Comment by alessandro-zomparelli** [comment]
Hi @alpoco from your screenshot seems that you are using the shipped version of the add-on, which is currently not working properly. Please try to use the latest release, it should work fine. Let me know!
