### ISSUE TITLE
how to use this on blender 2.8 ?

### ISSUE THREAD

**Issue by michelson** [alessandro-zomparelli/tissue#33]
Hi @alessandro-zomparelli , I've tried edge version of Tissue addon on blender 2.8 but I really don't know how to use this because there is no buttons added to the blender tools icons. It is supposed to add it to the blender tool bar ?

thanks

**Comment by JoelGodin** [comment]
Check these videos out for usage instructions.
https://www.youtube.com/user/alessandrozompa/featured

**Comment by michelson** [comment]
Thanks , got it!
