### ISSUE TITLE
2.8 version broken since most recent API change

### ISSUE THREAD

**Issue by MetinSeven** [alessandro-zomparelli/tissue#34]
Hi,

I'm very interested to try Tissue, but Blender 2.8's API had just changed again, causing many add-ons not to work anymore, including Tissue.

Many thanks in advance for fixing it.

Kind regards,

Metin

**Comment by Oxervision** [comment]
Hi, 
I have the same problem, many add-ons give an error when I try to activate them, this is the Error:
```
Traceback (most recent call last):
  File "/Applications/Blender/BLENDER 2.80/blender.app/Contents/Resources/2.80/scripts/modules/addon_utils.py", line 384, in enable
    mod.register()
  File "/Users/Oxer/Library/Application Support/Blender/2.80/scripts/addons/Tissue/__init__.py", line 105, in register
    bpy.utils.register_class(cls)
ValueError: register_class(...): already registered as a subclass
```
This message Error appears with other add-ons, how can I fix it? 

Regards,

Óscar

**Comment by alessandro-zomparelli** [comment]
Hi,
actually in the readme, you can find a link for the new version of Tissue for Blender 2.80:
https://github.com/alessandro-zomparelli/tissue/tree/b280-dev

Please, give a look to the wiki, because there have been some changes :-)
