### ISSUE TITLE
Tesselate doesn't work with Blender's builds from May 23 and 24

### ISSUE THREAD

**Issue by radionix3d** [alessandro-zomparelli/tissue#37]
![Blender 2019-05-24 10 56 49](https://user-images.githubusercontent.com/20736168/58311930-d33cd080-7e12-11e9-89b8-511ea8e94448.png)

Steps to reproduce - just do a tesselation operation on any mesh. Same goes with dual mesh (convert to dual mesh works though).

**Comment by alessandro-zomparelli** [comment]
Yes, I know. Unfortunately due to some API changes now it doesn't work. I changed some code, but apparently at the moment there is something missing in Blender API. I will try some turnaround... :-(

**Comment by alessandro-zomparelli** [comment]
Hi @radionix3d , I just uploaded a fixed version of Tissue: https://github.com/alessandro-zomparelli/tissue/releases/tag/v0-3-20

Please, let me know if you spot some errors somewhere.

**Comment by radionix3d** [comment]
thanks, now it works!
