### ISSUE TITLE
ModuleNotFoundError 

### ISSUE THREAD

**Issue by dimitarsp** [alessandro-zomparelli/tissue#42]
Trying to run the latest tissue (0.3.32) on the latest blender 2.81 (version: 2.81 (sub 3), branch: master, commit date: 2019-08-28 03:44, hash: `rBf88022b96f3a`)

`
Traceback (most recent call last):
  File "C:\Users\dimitar\Downloads\blender-2.81.0-git.f88022b96f3a-windows64\2.81\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'tissue'
`

The shipped version of tissue (0.3.25) loads and runs without a problem

**Comment by alessandro-zomparelli** [comment]
Hi Dimitar,
Thanks for reporting.
Now I'm don't have access to the PC, can you just try to manually paste the py files in the existing add-on folder and see if it works?

**Comment by dimitarsp** [comment]
Using a fresh daily version for some reason fixed the issue.
