### ISSUE TITLE
Numba pre-installed, but maybe there is an issue

### ISSUE THREAD

**Issue by enzyme69** [alessandro-zomparelli/tissue#47]
I am getting this weird error:
```
Collecting numba
Could not install packages due to an EnvironmentError: Could not find a suitable TLS CA certificate bundle, invalid path: /var/folders/r3/13y_zxhn0557ftnbz9xrt7x00000gn/T/tmpirxrgymy/pip-10.0.1-py2.py3-none-any.whl/pip/_vendor/certifi/cacert.pem
```

And when running Reaction Diffusion, it feels like it's doing nothing, or too slow.

**Comment by enzyme69** [comment]
I think manual install and copy paste the **numba** with **llvmlite** module is still easier... the built in install failed as I tried this on 2.80 and 2.82 alpha

**Comment by alessandro-zomparelli** [comment]
Hi @enzyme69 , I got the same issue on Ubuntu, Are you on Linux?

**Comment by sashorter** [comment]
FYI I can confirm the same error on Ubuntu with blender 2.80, 2.81 and 2.82.

**Comment by Oxervision** [comment]
I confirm the same error on macOS 10.13.6, Blender 2.81.16 & Tissue v0.3.37.
With Tissue v0.3.36 the error doesn't appear.

**Comment by alessandro-zomparelli** [comment]
Hi guys, Stephen Leger (Archipack developer) gave me support. Please try the new version on Mac:
https://github.com/alessandro-zomparelli/tissue/tree/b280-dev
This should also be a bit faster and you can also use vertex groups for different parameters.

**Comment by sashorter** [comment]
Confirmed that the b280-dev fixed the issue on Ubuntu.  Great work, AZ!

**Comment by Oxervision** [comment]
The b280-dev for me it works fine on macOS 10.13.6, Blender 2.81.16. 
Thanks!!

**Comment by alessandro-zomparelli** [comment]
Great, thanks to Stephen Leger!
