### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by lostchao11** [alessandro-zomparelli/tissue#48]
I did installation like it is write. It work but when I tried to tessellate an object it was giving me an error so I uninstalled it and tried to reinstall it but now I can't reinstall it. I even deleted the version that comes with blender and reinstalling still did not work. I'm wondering if you can add an update button straight into the default app.

**Comment by alessandro-zomparelli** [comment]
Hi @lostchao11 , I think that I know what's going on. Are you using Blender 2.80 installed on Windows?
If you are doing so, try to use the Blender installer to repair the previous Blender installation.

Otherwise, please try to share what you get in the Blender's Console.

**Comment by alessandro-zomparelli** [comment]
Hi @lostchao11 please, try with this version: https://github.com/alessandro-zomparelli/tissue/tree/b280-dev

**Comment by lostchao11** [comment]
Oh i'm so sorry I have not been on in a while. Got Blender installer tried repairing did not work.
Also I am useing Windows and it is Blender 2.80
I deleted blender and reinstalled it and i was able to check the box this time. But, here is a PNG of Blender Console when it was not working/unable to check the box.
![Blender's Console](https://user-images.githubusercontent.com/7042169/69031638-70765d00-098f-11ea-9286-e1c54a11d2da.png)

**Comment by alessandro-zomparelli** [comment]
Thanks @lostchao11 thanks for the update. It's great to hear that now it worked. I will close the issue then.
