### ISSUE TITLE
Error messages running the addon.

### ISSUE THREAD

**Issue by cheyennewy** [alessandro-zomparelli/tissue#49]
I get these error messages when I click on Mesh Tissue check box. 

![ERROR MESSAGES](https://user-images.githubusercontent.com/55920628/68904492-4dcc1600-06fb-11ea-843f-c1bddb09998d.png)

**Comment by alessandro-zomparelli** [comment]
Hi @cheyennewy 
This is what happened: unfortunately (in the previous version of Tissue), when installing Numba it automatically update the Numpy module. This can generate some issues on some systems (in my experience on Windows installed version).

You should be able to use the Blender installer to repair the Blender installation.
Now, thanks to Stephen Leger (Archipack add-on) it shouldn't happen again:
https://github.com/alessandro-zomparelli/tissue/releases/tag/v0-3-38

Please, let me know if it solve your issue.
