### ISSUE TITLE
Vertex Group parameter range min/max should be unbounded

### ISSUE THREAD

**Issue by sashorter** [alessandro-zomparelli/tissue#50]
I want a gradient effect that goes from unstable to stable F or K values, but the UI won't let me enter negative numbers.  Please consider the manual entry of "unsafe" parameters.

**Comment by alessandro-zomparelli** [comment]
Fixed, thanks for your feedback!
https://github.com/alessandro-zomparelli/tissue/releases/tag/v0-3-38
