### ISSUE TITLE
Multi component feature missing

### ISSUE THREAD

**Issue by lostchao11** [alessandro-zomparelli/tissue#57]
"   https://www.youtube.com/watch?v=pVNYyJeLGZI&t=30s  " skip to time 16:18 that is the feature im talking about

**Comment by alessandro-zomparelli** [comment]
Hi @lostchao11 , the feature is this:
![immagine](https://user-images.githubusercontent.com/6708848/71588192-e6d6b500-2b20-11ea-83f6-b28dc0585824.png)

It will automatically use the components that have a name matching with face's materials name
