### ISSUE TITLE
Question about g-code export

### ISSUE THREAD

**Issue by kosirm** [alessandro-zomparelli/tissue#61]
Hi, I'm having a lot of fun with your plugin, thank you so much for sharing this amazing project with all of us!
I'm wondering what is the purpose of g-code exporter in dev branch?
Because normal workflow for milling would be to export stl to some CAD/CAM package (e.g. Fusion 360 or Powermill) for setting toolpaths for 3D/4D/5D/6D milling. 
In the case of 3D printing normal workflow would be to export file to [Prusa Slicer](https://www.youtube.com/watch?v=bzf20FxsN2Q) (e.g. for Prusa printer) to fine-tune printing process there. Because, you know, "right tool for the right job"...
Or maybe I totally missed some special functionality of g-code exporter? Please let me know!

Speaking of import/export capabilities I would to suggest some text format (e.g. json) to export tessalation data. That way users of your plugin would easily exchange "tissues" among themselves, apply them to different objects or build templates for tessalations. For the ispiration I'm attaching [video of such capability in latest version of BY-GEN plugin](https://www.youtube.com/watch?v=kuskuvKKfcY&list=PLRKZHg6r5mu5iIL4ADCqSKCpYiRs4Ndky), which is also great plugin for generative modelling. Just my 0.2 $

**Comment by alessandro-zomparelli** [comment]
Hi Kosirm,
the aim of the gcode exporter is to draw your own tool path without slicing a mesh. If you just want to slice it, then a Slicing software would be much more appropriate, but if you want to make something more custom, then you can draw a polyline with variable thickness and define the path that you want with a variation in the quantity of extruded material (for example).
Here you can see some experiments that we are doing using that approach: 
https://www.facebook.com/claycodedesign/
https://www.instagram.com/stories/highlights/17942796004146281/

**Comment by alessandro-zomparelli** [comment]
Regarding the import/export settings for the Tessellation, that's a really nice idea. Before that there are many other things that I must do, but it could be really usefull. Thanks for your feedback.
Fo far you can just append an object in a new file and it will keep all the Tessellations settings. Not the same thing, but in the meanwhile is an option.

**Comment by kosirm** [comment]
Thanks for reply, now I do understand :) Man, your plugin is so inspiring... BR
