### ISSUE TITLE
Is it possible to add a license file?

### ISSUE THREAD

**Issue by Moult** [alessandro-zomparelli/tissue#64]
Would it be possible to add a license file, to make it clearer what the license is?

I'm adding the project to this list :)

https://wiki.osarch.org/index.php?title=AEC_Free_Software_directory

**Comment by alessandro-zomparelli** [comment]
Hi @Moult the license is GPL, there is a comment block at the beginning of each file. Shoul it be more specific?

**Comment by Moult** [comment]
Sorry, I meant like a `LICENSE` file at the root of the repo that can be picked up by scrapers or Github :) but that's OK if it's in each file too!

Closing bug.
