### ISSUE TITLE
Where is fill holes?

### ISSUE THREAD

**Issue by kosirm** [alessandro-zomparelli/tissue#66]
Hi, I just upgraded Tissue from 0.3.25 to 0.3.39 and now I can't find fill holes checkbox... I'm sorry to use issues as forum (I know it is not)... please let me know if there is any gitter/discord/etc. for such questions.
Anyway, it is still the most genious Blender addon... Please don't stop developing it!

**Comment by alessandro-zomparelli** [comment]
Hi @kosirm now is a bit different, but it is still there. You should activate the Merge and then you can chose if you want to bridge or cap the holes.
![image](https://user-images.githubusercontent.com/6708848/81875888-a92f7180-9581-11ea-8afb-6838cb87b546.png)
