### ISSUE TITLE
Convert to Dual Mesh doesn't work in 2.82a

### ISSUE THREAD

**Issue by vfxwillis** [alessandro-zomparelli/tissue#67]
Convert to Dual Mesh doesn't work in 2.82a.
The 'Other' is missing

**Comment by alessandro-zomparelli** [comment]
hi @vfxwillis for me it works fine, which version of Tissue are you using? Can you send me a screenshot?

**Comment by vfxwillis** [comment]
[image: image.png]
[image: image.png]

Hi Alessandro,
here is my screenshot, thanks for your help

Alessandro Zomparelli <notifications@github.com> 于2020年5月14日周四 上午7:28写道：

**Comment by alessandro-zomparelli** [comment]
sorry @vfxwillis  but I can't see the images

**Comment by markedagain** [comment]
https://i.imgur.com/t8LK45X.jpeg

**Comment by markedagain** [comment]
I can confirm installing manually ie: following your instructions lol, all worked fine. seems the default one that comes shipped is broken or missing things

**Comment by alessandro-zomparelli** [comment]
Yes, I confirm that de shipped one is broken. I'll ask to fix that. I'm just procrastinating because Tissue is constantly evolving :-P
