### ISSUE TITLE
Patch no longer works in at least 2.82

### ISSUE THREAD

**Issue by zutils** [alessandro-zomparelli/tissue#68]
When setting patch, items get generated, but no tessellation changes: 
_tissue_tmp_base_apply_mod
_tissue_tmp_base_before_subs
...and what looks like a flattened clone of the component.

Not knowing what patch does, I'm pretty sure what I am seeing is not accurate. My belief is that it does the same thing as Quad, but covers the entire polygon instead of just the first 4 vertices. Regardless - something is up with that :)

**Comment by alessandro-zomparelli** [comment]
Hi @zutils this should be a bug, I fixed some things recently though:
https://github.com/alessandro-zomparelli/tissue/tree/b280-dev
Regarding the meaning of the Patch mode, it's not for polygons, but for quad faces with subdivision surface. This may help: https://youtu.be/pVNYyJeLGZI?t=348
