### ISSUE TITLE
Tissue says numba is installed correctly but performance says otherwise.

### ISSUE THREAD

**Issue by billhails** [alessandro-zomparelli/tissue#74]
First of all, thanks for this great add-on.
Blender: 2.83.3
Tissue: 0-3-44
MacOS Mojave 10.14.6

Fresh install of Blender 2.83.3 yesterday, then installed tissue 0-3-44 from the .zip
Tissue says "Numba installed correctly", however I'm familiar with the performance boost it provides from previous versions, and when I try reaction/diffusion on an out-of-the-box torus with an applied subsurf level 3, I'm getting only around 0.2 fps while running the simulation. Nothing else in the scene other than the torus.

In a previous (2.82?) blender I was able to install numba manually into the blender/python libs with a combination of `source bin/activate` and `pip install` but those don't seem to be part of 2.83.3.

It feels like you're developing against a moving target so you have my sympathies, keep up the good work! :-)

**Comment by alessandro-zomparelli** [comment]
hi @billhails yes, that was exactly the feeling :-P

Please, try it now, I should have fixed that in the development branch. If it is working properly, than I will merge with the Master.
https://github.com/alessandro-zomparelli/tissue/tree/b280-dev

Thanks for reporting,

Alessandro

**Comment by billhails** [comment]
Yes it works now! ~6.5 fps from exactly the same configuration.
Thanks so much for the quick response.

By the way, why a torus? because if you unwrap it and convert to vertex colours the texture is tile-able.

**Comment by alessandro-zomparelli** [comment]
Oh, cool. I didn't though about that. Smart :-)
