### ISSUE TITLE
dual mesh

### ISSUE THREAD

**Issue by kostex** [alessandro-zomparelli/tissue#75]
in dual_mesh.py on line 246, latest blender doesn't like the "apply_as" (anymore)
removing it solves error messages generated..

            bpy.ops.object.modifier_apply(
                    apply_as='DATA', modifier='dual_mesh_subsurf'
                    )

**Comment by alessandro-zomparelli** [comment]
Hi @kostex , I assume that you are referring to Blender 2.90, right? Thanks for reporting that, I will fix in the next uploads.

**Comment by alessandro-zomparelli** [comment]
Hi @kostex it's fixed in the development branch: https://github.com/alessandro-zomparelli/tissue/tree/b280-dev
thanks for spotting that!
