### ISSUE TITLE
2.90.1 compatible ?

### ISSUE THREAD

**Issue by michelson** [alessandro-zomparelli/tissue#80]
Hi @alessandro-zomparelli , is tissue 2.90.1 compatible, I've just added it but it does not show in the interface

**Comment by JoelGodin** [comment]
Yes, I use it on 2.91.0 ( I think that is what you asked.) Hit 'N' to bring up the sidepanel, and it is there.
![1](https://user-images.githubusercontent.com/9205295/94629298-4ddff080-0290-11eb-9615-cb28f9982539.png)

**Comment by michelson** [comment]
uhmm... somehow the plugin does is not visible

![image](https://user-images.githubusercontent.com/11976/94643493-54389180-02bd-11eb-919a-ab3513464688.png)

![image](https://user-images.githubusercontent.com/11976/94643542-6d414280-02bd-11eb-9ce5-da1e9bea27cc.png)

btw, 2.90.1 version is stated on blender site https://www.blender.org/download/

**Comment by onerawartist** [comment]
You should add the github version , the most updated one.

**Comment by alessandro-zomparelli** [comment]
@onerawartist you are right... my issue is that I'm always adding something :-P I will fix the last things and then I'll try to take care of that.

**Comment by seanr** [comment]
@michelson looks like you're in edit mode, but the other screenshot is in object mode.
