### ISSUE TITLE
Error running Tissue

### ISSUE THREAD

**Issue by manfrog** [alessandro-zomparelli/tissue#82]
Hi, I'm not sure what is happening, but this is the error that pops up when I try to use Tissue in 2.90.1
Any help would be much appreciated! Thanks!

Traceback (most recent call last):
  File "C:\Users\Biggles\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\tissue-0-3-44\dual_mesh.py", line 247, in execute
    apply_as='DATA', modifier='dual_mesh_subsurf'
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "apply_as" unrecognized

location: <unknown location>:-1

**Comment by alessandro-zomparelli** [comment]
Hi @manfrog , are you using the latest version? That issue should be already fixed.

**Comment by manfrog** [comment]
Hi Alessandro, sorry for the slow reply. It's version 0.3.44 which I downloaded from github. It only happens with the old "convert to Dual Mesh" tool, so It's not really a problem. I can use the "Dual Mesh" button at the top, and it works fine.

**Comment by alessandro-zomparelli** [comment]
Hi @manfrog I just updated the master branch of Tissue for Blender 2.91. I think that the issue is not there anymore.
