### ISSUE TITLE
Tesselating object using only the selected faces is this possible?

### ISSUE THREAD

**Issue by stillpointx** [alessandro-zomparelli/tissue#83]
I'm wondering if it's possible just to tessellate selected faces only?  I'm using ubuntu 20.04 Blender 2.91.0

Example: 
I want to use object one, and place / tessellate that onto only the selected faces of object 2.

Is this possible? if not do you know of a workaround / can you add it to the wishlist in tissue

![screenshot-2020-11-27-02-06-57](https://user-images.githubusercontent.com/28985314/100420956-73e9fd00-3055-11eb-8bac-6bead0ddccba.png)

**Comment by alessandro-zomparelli** [comment]
Yes, it's possible. You can use the selected faces or faces by Material ID:
![image](https://user-images.githubusercontent.com/6708848/100436296-740eea80-309f-11eb-8876-b52ba6d02e0f.png)

You can do even more complex things: https://www.youtube.com/watch?v=9RDIQvBB8XQ&ab_channel=AlessandroZomparelli

**Comment by stillpointx** [comment]
Thanks!!!  Great addon!!!
