### ISSUE TITLE
Rotating Tessellate selected faces using Ubuntu 20.04 and Blender 2.91.0

### ISSUE THREAD

**Issue by stillpointx** [alessandro-zomparelli/tissue#84]
I'm able to add an object to selected faces and tessellate it see animation below

![on_selected_faces](https://user-images.githubusercontent.com/28985314/100495649-93e3f400-311b-11eb-9cb2-3400a67eb493.gif)

It creates this:
![screenshot-2020-11-28-03-00-06](https://user-images.githubusercontent.com/28985314/100496901-ea563000-3125-11eb-8b00-1474d36cc4dc.png)

But how can I rotate it so the seem is top to bottom see example below
![screenshot-2020-11-28-01-52-47](https://user-images.githubusercontent.com/28985314/100495733-7bc0a480-311c-11eb-8f1c-ad3530d925a3.png)

I tried following this but the rotate option doesn't seem to come up with the selected faces
https://youtu.be/PRIcB1Q-gK4?t=897

**Comment by onerawartist** [comment]
Go to top view and rotate the component '' the small object you are using for tessellation. I believe that shour give you the result you are expecting

**Comment by alessandro-zomparelli** [comment]
Yes, thanks @onerawartist this would work, but only if you rotate it in Edit-mode (unless he is using the Global Coordinates for the component).

The easiest thing to do, though, is to use the Shift option in the rotation:
![image](https://user-images.githubusercontent.com/6708848/100514841-36ca5b80-3178-11eb-859c-3a4ad12acccf.png)
For that @stillpointx , you should download an updated version of Tissue, don't use the default one, that has some missing parts. Download this version that I just updated for Blender 2.91: https://github.com/alessandro-zomparelli/tissue

**Comment by stillpointx** [comment]
Thanks I'll give it try.  Just to let you know one of the links seems to be giving a 404
![screenshot-2020-11-28-07-36-00](https://user-images.githubusercontent.com/28985314/100515805-ac203700-314c-11eb-950a-747327aa8160.png)
![screenshot-2020-11-28-07-36-36](https://user-images.githubusercontent.com/28985314/100515808-b04c5480-314c-11eb-94e7-d935dfb77b7a.png)

**Comment by JoelGodin** [comment]
Should be this;
https://github.com/alessandro-zomparelli/tissue/tree/b290-dev

**Comment by alessandro-zomparelli** [comment]
Hi @stillpointx yes, that link is not there yet, I'm in the process of fixing this. Currently, the master branch is updated to b290-dev, my development branch for the Blender 2.9x series. 
I still must correct a couple of minor things and then I will create the official release. Sorry for the inconvenience.

**Comment by stillpointx** [comment]
@alessandro-zomparelli no inconvenience at all I love this ad-don.

**Comment by stillpointx** [comment]
Thanks the new update fixed it. :)
