### ISSUE TITLE
Suggestion : Random component selection

### ISSUE THREAD

**Issue by Memesphere** [alessandro-zomparelli/tissue#88]
For multi-component selection a face is mapped to one component with the same name as the face material. To create more variation in the resulting branching system it would useful to map faces to a component selected randomly from a collection. The collection could carry the same name as the face material.

**Comment by alessandro-zomparelli** [comment]
Thanks @alessandro-zomparelli for the suggestion. This is actually interesting, and it may lead also to other possible implementations of more possible strategies. It's something that I will try in the future.
Before that, you may consider using the Random Material operator that randomize the Materials. It's not seamless but still can make the trick for a single iteration. It's more complex for multiple iterations.

**Comment by alessandro-zomparelli** [comment]
@Memesphere I'm currently working on that feature, I will update you once it's ready. 
Thanks again for your suggestion :-)

**Comment by Memesphere** [comment]
> @Memesphere I'm currently working on that feature, I will update you once it's ready.
> Thanks again for your suggestion :-)

Looking forward to it.

**Comment by alessandro-zomparelli** [comment]
hi @Memesphere it's finally online :-) https://github.com/alessandro-zomparelli/tissue/tree/b290-dev

There are now three different options for the Tessellation, the classic one with the selected object as a component, plus one based on the Active Collection, and one that uses the Materials names (former Multi-Components):
![image](https://user-images.githubusercontent.com/6708848/106400928-a7645180-6421-11eb-84b1-d922e5a0bcb4.png)

More options in the Tissue properties panel, under Object Data:
![image](https://user-images.githubusercontent.com/6708848/106400951-c367f300-6421-11eb-9dba-233a1f269f30.png)

Let me know your thoughts!
