### ISSUE TITLE
Looping a mesh pattern inside and outside of a cone shape

### ISSUE THREAD

**Issue by stillpointx** [alessandro-zomparelli/tissue#89]
I'm trying to create a mesh pattern that loops inside and outside of a cone shape similar to the torus below with the red band that starts and finishes at the same place / face but using a cone shape

![screenshot-2020-12-10-02-43-42](https://user-images.githubusercontent.com/28985314/101736787-efa26b80-3a91-11eb-8809-a8e5c84f3d13.png)

![vokoscreen-2020-12-10_03-00-13](https://user-images.githubusercontent.com/28985314/101738374-106bc080-3a94-11eb-9b1f-40f95e355667.gif)

**Cone shape:**
![screenshot-2020-12-10-02-44-06](https://user-images.githubusercontent.com/28985314/101736849-0943b300-3a92-11eb-9879-d4cabf0b2e50.png)

Is this possible?

I tried using the diamond shape but it didn't even come close to looping any ideas how to do this?
![screenshot-2020-12-10-02-44-30](https://user-images.githubusercontent.com/28985314/101736886-1496de80-3a92-11eb-9555-6fd318559b85.png)

[diamond cone loop pattern.blend.zip](https://github.com/alessandro-zomparelli/tissue/files/5671054/diamond.cone.loop.pattern.blend.zip)

PS: I'm using Tissue 0.3.48 on Ubuntu 20.04 and Blender 2.91
Thanks.

**Comment by alessandro-zomparelli** [comment]
hi @stillpointx you should use "Dissolve Seams", selectable after activating the "Merge" of the pieces. 
Before that, select the boundary edges of your component and use "Mark Seams"

**Comment by stillpointx** [comment]
I can find everything but the option to "mark seams".

![screenshot-2020-12-10-08-40-50](https://user-images.githubusercontent.com/28985314/101779615-7d4a7f00-3ac3-11eb-9245-e6d3b2388878.png)

**Comment by JoelGodin** [comment]
That is a blender function in edit mode.
![1111](https://user-images.githubusercontent.com/9205295/101784131-1a5be680-3ac9-11eb-93e6-06b4db7c65e9.png)

**Comment by stillpointx** [comment]
Thanks, I gave that a shot

1)  Making seams at the top and the bottom

![screenshot-2020-12-10-23-54-27](https://user-images.githubusercontent.com/28985314/101865376-13be8500-3b44-11eb-8833-87c93f0c7563.png)

![screenshot-2020-12-10-23-55-10](https://user-images.githubusercontent.com/28985314/101865399-2638be80-3b44-11eb-9f16-8b4635601155.png)

2) Then I adjusted the distance.
![screenshot-2020-12-11-00-01-10](https://user-images.githubusercontent.com/28985314/101865417-35b80780-3b44-11eb-84b1-fbf217e754fa.png)

But issues still popped up any other suggestions?

![screenshot-2020-12-11-00-00-13](https://user-images.githubusercontent.com/28985314/101865450-4d8f8b80-3b44-11eb-8da3-208180c7d8f3.png)

**Comment by onerawartist** [comment]
![01](https://user-images.githubusercontent.com/71472224/101867657-fb6a5c80-3b7b-11eb-8152-fd09c6117702.jpg)
is this what you are looking for ?

**Comment by stillpointx** [comment]
Close,

I was going for something like this which if you Alt-Left Click a face it selects the corresponding loop. (note I made this with the simple deform modifier using stretch) but it messes up the top and bottom.

![screenshot-2020-12-11-00-54-46](https://user-images.githubusercontent.com/28985314/101868615-bcbcae00-3b4b-11eb-8107-4c1d87d838d7.png)

**Comment by alessandro-zomparelli** [comment]
Hi @stillpointx ,
I think you added the seams in the base object. You should add them to the component:
![image](https://user-images.githubusercontent.com/6708848/101892003-1ac8b000-3ba3-11eb-87cf-015487c9ff70.png)

**Comment by stillpointx** [comment]
@alessandro-zomparelli thanks that did it.   I'm going to test it out to see how it works with different shapes.

Thanks Again!
