### ISSUE TITLE
Strange edge ghost artifacting 

### ISSUE THREAD

**Issue by stillpointx** [alessandro-zomparelli/tissue#90]
Strange edge ghost artifacting after tessellation

![screenshot-2020-12-12-01-06-50](https://user-images.githubusercontent.com/28985314/101976975-4df95680-3c18-11eb-8b7d-4d6b6838c9a6.png)

I created a video of how I created it and included the blend file.
![video ghost edges](https://user-images.githubusercontent.com/28985314/101976898-c27fc580-3c17-11eb-9e9d-69fabed5c046.gif)

It's like it's creating "ghost edges"  I'm not sure if this is a Blender issue or
just the way the plug-in works.

Zipped File:
[ghost_edges.zip](https://github.com/alessandro-zomparelli/tissue/files/5682582/ghost_edges.zip)

PS: I'm using Tissue 0.3.48 on Ubuntu 20.04 and Blender 2.91
Thanks.

**Comment by JoelGodin** [comment]
It's a 3D graphics issue in that you have non-planar quads.  The software can't figure out how to shade it.
In this video attached, you have to manually fix that by selecting those faces, then Face>Triangulate faces.
That will fix some. Others you have to delete the triangles created, the fill in new ones. 
(that is my understanding, there may be something that can be done before tessellating that I'm not aware of)
https://youtu.be/Qp2iOcAlKMA

**Comment by alessandro-zomparelli** [comment]
As @JoelGodin is suggesting, that's a 3D issue. Your faces are really distorted, and for viewport rendering, they have to be split into triangles, seems that the diagonal is different every time. The fix for that depends on what are your needs for such a mesh object...
I see two options, triangulate or subdivision surface (catmull-clark or simple).

**Comment by stillpointx** [comment]
Thanks!  adding a subdivision surface fixed it.
