### ISSUE TITLE
component coordinates

### ISSUE THREAD

**Issue by piethonbea** [alessandro-zomparelli/tissue#96]
Hello! I installed tissue because of a feature I really liked which is tessellate. The problem is that I am trying to include the components coordinates option and it is not showing up. I want to be able to use the bounds option. How can I fix that?

**Comment by alessandro-zomparelli** [comment]
hi @piethonbea , can you please show me a screenshot of what you see? 
In the latest versions of Tissue, when you use the Tessellation it shows a limited number of settings.
![image](https://user-images.githubusercontent.com/6708848/106595627-1e9a0280-6554-11eb-91cb-3fa325fda7c6.png)

After that, you can edit all the controls in the Object Data panel:
![image](https://user-images.githubusercontent.com/6708848/106595695-38d3e080-6554-11eb-89e7-11f2c3ecf448.png)

**Comment by piethonbea** [comment]
Hello!

I did see exactly like this. I downloaded blender just to use this feature haha so I wasn’t sure how object data worked or where it was. I can see all the options now thank you so much!

Regards,

Beatriz

________________________________
