### ISSUE TITLE
Incompatibility with Blender 2.91?

### ISSUE THREAD

**Issue by VeganDan** [alessandro-zomparelli/tissue#99]
There is no "Tissue" tab when pressing "N" menu on Blender version 2.91. It only appears inside the "Edit" tab.  The tutorial "Daily Blender Tip 137 - Tissue Add-on: Experiment 3" (a means to make broccoli) sadly cannot be replicated.

**Comment by alessandro-zomparelli** [comment]
Hi @VeganDan , don't worry, there is no incompatibility :-)
I think the tutorial that you are mentioning is based on my video: https://www.youtube.com/watch?v=N-fNCdjNztk&t=542s
Already for Blender 2.80 I updated it according to the new interface (a slightly different approach also): https://www.youtube.com/watch?v=7Liv--XSaCg&t=1s

Now Tissue is organized a bit differently compared to version 2.79, but all the old features, together with new ones are still there.
Let me know if you have any problems.

**Comment by JoelGodin** [comment]
I think he is talking about this tab.  It is there for me on 2.91 and 2.91.2 stable and even nightly builds.
![tissue](https://user-images.githubusercontent.com/9205295/107123430-7e9deb00-686b-11eb-8e9f-b05fd38d5fa3.png)

**Comment by VeganDan** [comment]
Thank you for the clarification. It is appreciated!! The tab is indeed missing as stated. If I can make it appear then perhaps the full features will appear. May try resetting all or redownloading Blender 3D. Thanks again for the great work!

**Comment by alessandro-zomparelli** [comment]
@VeganDan the version of Tissue that is shipped with Blender is kind of broken They put only a few operators under the Edit panel. Install this instead: https://github.com/alessandro-zomparelli/tissue/tree/b290-dev

**Comment by VeganDan** [comment]
THANK YOU! The new addon appears to be working! Will keep you posted on any new developments.

**Comment by tstaiye** [comment]
> 
> 
> @VeganDan the version of Tissue that is shipped with Blender is kind of broken They put only a few operators under the Edit panel. Install this instead: https://github.com/alessandro-zomparelli/tissue/tree/b290-dev

Huge thanks, spent an hour before coming here. Now everything works
